import type { HistoryData, MonthlyData } from "@/lib/water-types"

export function exportToCSV(data: HistoryData[] | MonthlyData[], filename: string) {
  let csvContent = ""
  
  if (data.length === 0) return

  // Check if it's history data or monthly data
  const isHistory = "cold" in data[0]
  
  if (isHistory) {
    csvContent = "Date,Cold Water (L),Cost\n"
    ;(data as HistoryData[]).forEach((row) => {
      csvContent += `${row.date},${row.cold},${row.cost}\n`
    })
  } else {
    csvContent = "Month,Usage (L),Cost\n"
    ;(data as MonthlyData[]).forEach((row) => {
      csvContent += `${row.month},${row.usage},${row.cost}\n`
    })
  }

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" })
  downloadBlob(blob, `${filename}.csv`)
}

export function exportToPDF(
  data: HistoryData[] | MonthlyData[],
  filename: string,
  title: string,
  formatCurrency: (amount: number) => string
) {
  // Create a simple text-based PDF-like report
  let content = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body { font-family: 'Helvetica', 'Arial', sans-serif; padding: 40px; color: #1a365d; }
    h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e2e8f0; }
    th { background-color: #f1f5f9; font-weight: 600; }
    tr:hover { background-color: #f8fafc; }
    .total { font-weight: bold; background-color: #e0f2fe; }
    .header { display: flex; justify-content: space-between; align-items: center; }
    .logo { font-size: 24px; font-weight: bold; color: #2563eb; }
    .date { color: #64748b; }
    @media print {
      body { padding: 20px; }
      button { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">SmartFaucet</div>
    <div class="date">${new Date().toLocaleDateString()}</div>
  </div>
  <h1>${title}</h1>
`

  const isHistory = "cold" in data[0]
  
  if (isHistory) {
    const historyData = data as HistoryData[]
    const totalCold = historyData.reduce((sum, r) => sum + r.cold, 0)
    const totalCost = historyData.reduce((sum, r) => sum + r.cost, 0)

    content += `
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Cold Water (L)</th>
        <th>Cost</th>
      </tr>
    </thead>
    <tbody>
`
    historyData.forEach((row) => {
      content += `
      <tr>
        <td>${row.date}</td>
        <td>${row.cold}</td>
        <td>${formatCurrency(row.cost)}</td>
      </tr>
`
    })

    content += `
      <tr class="total">
        <td>Total</td>
        <td>${totalCold}</td>
        <td>${formatCurrency(totalCost)}</td>
      </tr>
    </tbody>
  </table>
`
  } else {
    const monthlyData = data as MonthlyData[]
    const totalUsage = monthlyData.reduce((sum, r) => sum + r.usage, 0)
    const totalCost = monthlyData.reduce((sum, r) => sum + r.cost, 0)

    content += `
  <table>
    <thead>
      <tr>
        <th>Month</th>
        <th>Usage (L)</th>
        <th>Cost</th>
      </tr>
    </thead>
    <tbody>
`
    monthlyData.forEach((row) => {
      content += `
      <tr>
        <td>${row.month}</td>
        <td>${row.usage.toLocaleString()}</td>
        <td>${formatCurrency(row.cost)}</td>
      </tr>
`
    })

    content += `
      <tr class="total">
        <td>Total</td>
        <td>${totalUsage.toLocaleString()}</td>
        <td>${formatCurrency(totalCost)}</td>
      </tr>
    </tbody>
  </table>
`
  }

  content += `
  <p style="margin-top: 30px; color: #64748b; font-size: 12px;">
    Generated by SmartFaucet Dashboard on ${new Date().toLocaleString()}
  </p>
  <script>
    window.onload = function() { window.print(); }
  </script>
</body>
</html>
`

  const blob = new Blob([content], { type: "text/html;charset=utf-8" })
  const url = URL.createObjectURL(blob)
  const printWindow = window.open(url, "_blank")
  if (printWindow) {
    printWindow.onafterprint = () => {
      URL.revokeObjectURL(url)
    }
  }
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const link = document.createElement("a")
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

export function exportJSON(data: unknown, filename: string) {
  const jsonContent = JSON.stringify(data, null, 2)
  const blob = new Blob([jsonContent], { type: "application/json" })
  downloadBlob(blob, `${filename}.json`)
}
