"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

export type Language = "ja" | "en" | "mn"
export type Currency = "JPY" | "USD" | "MNT"

interface SettingsContextType {
  language: Language
  setLanguage: (lang: Language) => void
  currency: Currency
  setCurrency: (curr: Currency) => void
  t: (key: string) => string
  formatCurrency: (amount: number) => string
}

const translations: Record<Language, Record<string, string>> = {
  ja: {
    dashboard: "ダッシュボード",
    control: "水道制御",
    history: "使用履歴",
    analytics: "分析",
    presets: "プリセット",
    settings: "設定",
    realTimeUsage: "リアルタイム使用量",
    waterFlow: "水流",
    temperature: "温度",
    cost: "コスト",
    liters: "リットル",
    cold: "冷水",
    warm: "温水",
    hot: "熱水",
    currentUsage: "現在の使用量",
    todayUsage: "本日の使用量",
    monthlyUsage: "今月の使用量",
    waterControl: "水道制御",
    setTemperature: "温度設定",
    setLimit: "制限設定",
    byLiters: "リットル制限",
    byTime: "時間制限",
    estimatedCost: "予想コスト",
    start: "開始",
    stop: "停止",
    safety: "安全通知",
    notifications: "通知",
    overuseAlert: "過剰使用警告",
    normalUsage: "通常使用",
    limitExceeded: "制限超過",
    usageHistory: "使用履歴",
    last7Days: "過去7日間",
    coldWater: "冷水",
    warmWater: "温水",
    hotWater: "熱水",
    monthlyComparison: "月間比較",
    currentMonth: "今月",
    lastMonth: "先月",
    increase: "増加",
    decrease: "減少",
    ecoEfficiency: "エコ効率",
    good: "良好",
    average: "平均",
    high: "高",
    savingTips: "節水のヒント",
    smartPresets: "スマートプリセット",
    shower: "シャワー",
    bath: "お風呂",
    kitchen: "キッチン",
    edit: "編集",
    save: "保存",
    cancel: "キャンセル",
    costEfficiency: "コスト効率",
    low: "低",
    medium: "中",
    language: "言語",
    currencyLabel: "通貨",
    minutes: "分",
    seconds: "秒",
    flowRate: "流量",
    perMinute: "/ 分",
    active: "アクティブ",
    inactive: "非アクティブ",
    autoShutoff: "自動停止",
    enabled: "有効",
    disabled: "無効",
    selectPreset: "プリセットを選択",
    customSettings: "カスタム設定",
    applyPreset: "プリセットを適用",
    editPreset: "プリセットを編集",
    presetName: "プリセット名",
    temperatureRange: "温度範囲",
    waterLimit: "水量制限",
    duration: "時間",
    close: "閉じる",
    login: "ログイン",
    register: "新規登録",
    logout: "ログアウト",
    email: "メールアドレス",
    password: "パスワード",
    confirmPassword: "パスワード確認",
    name: "名前",
    welcomeBack: "おかえりなさい",
    createAccount: "アカウント作成",
    demoCredentials: "デモ認証情報",
    devices: "デバイス",
    scanDevices: "デバイススキャン",
    noDevices: "デバイスが見つかりません",
    pairDevice: "ペアリング",
    removeDevice: "削除",
    syncDevice: "同期",
    deviceStatus: "デバイス状態",
    online: "オンライン",
    offline: "オフライン",
    signalStrength: "信号強度",
    firmwareVersion: "ファームウェア",
    lastSeen: "最終接続",
    connectionLogs: "接続ログ",
    notifications: "通知",
    markAllRead: "すべて既読",
    clearAll: "すべてクリア",
    noNotifications: "通知はありません",
    enableNotifications: "通知を有効にする",
    export: "エクスポート",
    exportCSV: "CSV出力",
    exportPDF: "PDF出力",
    profile: "プロフィール",
    account: "アカウント",
    memberSince: "登録日",
    usageReport: "使用量レポート",
    dailyReport: "日次レポート",
    monthlyReport: "月次レポート",
    scanning: "スキャン中...",
    syncing: "同期中...",
    battery: "バッテリー",
    location: "場所",
    continueWithGoogle: "Googleで続ける",
    orContinueWith: "または",
    orTryDemo: "またはデモを試す",
    dashboardSubtitle: "リアルタイムで水道使用量を確認",
    loginSubtitle: "メールとパスワード、またはGoogle。",
    registerSubtitle: "メールとパスワードで登録、またはGoogle。",
    signedInAs: "ログイン中",
    registerSignedInNote: "別のメールが必要な場合は先にログアウトしてください。",
    forgotPassword: "パスワードをお忘れですか？",
    authNoAccount: "アカウントをお持ちでないですか？",
    authHaveAccount: "すでにアカウントをお持ちですか？",
    passwordMismatch: "パスワードが一致しません",
    passwordMinLength: "パスワードは6文字以上にしてください",
    firebaseNotConfigured:
      "Firebaseが未設定です。.env.local に NEXT_PUBLIC_FIREBASE_* を追加してください（.env.example参照）。",
    devicesLine: "{n} 台 — BLE（ESP32-C6 + YF-B7）",
    devicesBleStack: "BLE（ESP32-C6 + YF-B7）",
    devicesEmptyHint:
      "ESP32-C6（SmartFaucet BLE）をスキャン。接続後ダッシュボードに流量が表示されます。",
    pairDialogDescription:
      "SmartFaucet ファームウェアの ESP32-C6（YF-B7 流量センサー）をスキャン。Bluetooth許可に同意してください。",
    bleScanningTitle: "BLE周辺機器をスキャン中…",
    bleScanningHint: "約12秒 · 先にESP32の電源を入れてください",
    foundLabel: "見つかった機器",
    connect: "接続",
    historySubtitle: "日次の冷水使用量（リットル）とコスト",
    historyDailyColdDesc: "日次の冷水（リットル）",
    historyDailySpendDesc: "日次の支出",
    noHistoryData: "履歴データはまだありません",
    noCostTrendData: "コスト推移データはまだありません",
    chartUsageTrend: "使用量の推移",
    chartLast6MonthsWater: "過去6ヶ月の水道使用量",
    chartCostTrend: "コストの推移",
    chartLast6MonthsSpend: "過去6ヶ月の支出",
    noUsageData: "使用量データはまだありません",
    noCostData: "コストデータはまだありません",
    weeklyComparison: "週間比較",
    weeklyComparisonDesc: "過去4週間の使用量と1日平均",
    noWeeklyData: "週次データはまだありません",
    chartTotalUsage: "合計使用量",
    chartDailyAvg: "1日平均",
    smartSuggestions: "おすすめ",
    smartSuggestionsDesc: "使用パターンに基づくヒント",
    noAiSuggestions: "まだ提案はありません。データが溜まると表示されます。",
    ecoGreat: "平均より少なめです。良いです！",
    ecoNormal: "使用量は通常の範囲内です",
    ecoHigh: "使用量を減らすことを検討してください",
    tooltipUsage: "使用量",
    analyticsPageSubtitle: "使用量の傾向を分析し、節水のヒントを見つけましょう",
    savingTipsDesc: "簡単な節水でコストも抑えられます",
    profileAccountDesc: "アカウント情報を管理します",
    notificationsSettingsDesc: "プッシュ通知の設定",
    notifEnabledStatus: "通知はオンです",
    notifBlockedStatus: "通知がブロックされています",
    notifPromptStatus: "ブラウザの通知を許可してください",
    notifEnableInBrowserSettings: "ブラウザの設定で通知を許可してください",
    exportDataDesc: "水道使用量データをダウンロード",
    dailyReportDesc: "直近7日間のデータ",
    monthlyReportDesc: "過去6ヶ月の履歴データ",
    exportJSONLabel: "JSONをエクスポート",
    loading: "読み込み中…",
    redirectingToSignIn: "サインインへ移動中…",
    resetPassword: "パスワードをリセット",
    resetPasswordEnterEmail:
      "メールアドレスを入力すると、リセット用のリンクをお送りします。",
    resetPasswordEmailSent: "メールを送信しました",
    resetPasswordEmailSentBody:
      "{email} にアカウントがあれば、まもなくパスワード再設定のリンクが届きます。",
    resetPasswordCheckEmailInstructions:
      "受信トレイを確認し、メールの手順に従ってパスワードを再設定してください。",
    sendResetLink: "リセットリンクを送信",
    backToLogin: "ログインに戻る",
    emailPlaceholder: "your@email.com",
    authErrorTitle: "認証エラー",
    authErrorSomethingWrong: "サインイン中に問題が発生しました。もう一度お試しください。",
    authErrorWithCode: "エラー: {error}",
    chartLitersPerDay: "L/日",
  },
  en: {
    dashboard: "Dashboard",
    control: "Control",
    history: "History",
    analytics: "Analytics",
    presets: "Presets",
    settings: "Settings",
    realTimeUsage: "Real-time Usage",
    waterFlow: "Water Flow",
    temperature: "Temperature",
    cost: "Cost",
    liters: "Liters",
    cold: "Cold",
    warm: "Warm",
    hot: "Hot",
    currentUsage: "Current Usage",
    todayUsage: "Today's Usage",
    monthlyUsage: "Monthly Usage",
    waterControl: "Water Control",
    setTemperature: "Set Temperature",
    setLimit: "Set Limit",
    byLiters: "By Liters",
    byTime: "By Time",
    estimatedCost: "Estimated Cost",
    start: "Start",
    stop: "Stop",
    safety: "Safety",
    notifications: "Notifications",
    overuseAlert: "Overuse Alert",
    normalUsage: "Normal Usage",
    limitExceeded: "Limit Exceeded",
    usageHistory: "Usage History",
    last7Days: "Last 7 Days",
    coldWater: "Cold Water",
    warmWater: "Warm Water",
    hotWater: "Hot Water",
    monthlyComparison: "Monthly Comparison",
    currentMonth: "Current Month",
    lastMonth: "Last Month",
    increase: "Increase",
    decrease: "Decrease",
    ecoEfficiency: "Eco Efficiency",
    good: "Good",
    average: "Average",
    high: "High",
    savingTips: "Water Saving Tips",
    smartPresets: "Smart Presets",
    shower: "Shower",
    bath: "Bath Fill",
    kitchen: "Kitchen",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    costEfficiency: "Cost Efficiency",
    low: "Low",
    medium: "Medium",
    language: "Language",
    currencyLabel: "Currency",
    minutes: "min",
    seconds: "sec",
    flowRate: "Flow Rate",
    perMinute: "/ min",
    active: "Active",
    inactive: "Inactive",
    autoShutoff: "Auto Shutoff",
    enabled: "Enabled",
    disabled: "Disabled",
    selectPreset: "Select Preset",
    customSettings: "Custom Settings",
    applyPreset: "Apply Preset",
    editPreset: "Edit Preset",
    presetName: "Preset Name",
    temperatureRange: "Temperature Range",
    waterLimit: "Water Limit",
    duration: "Duration",
    close: "Close",
    login: "Login",
    register: "Register",
    logout: "Logout",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    name: "Name",
    welcomeBack: "Welcome Back",
    createAccount: "Create Account",
    demoCredentials: "Demo Credentials",
    devices: "Devices",
    scanDevices: "Scan Devices",
    noDevices: "No devices found",
    pairDevice: "Pair",
    removeDevice: "Remove",
    syncDevice: "Sync",
    deviceStatus: "Device Status",
    online: "Online",
    offline: "Offline",
    signalStrength: "Signal Strength",
    firmwareVersion: "Firmware",
    lastSeen: "Last Seen",
    connectionLogs: "Connection Logs",
    notifications: "Notifications",
    markAllRead: "Mark All Read",
    clearAll: "Clear All",
    noNotifications: "No notifications",
    enableNotifications: "Enable Notifications",
    export: "Export",
    exportCSV: "Export CSV",
    exportPDF: "Export PDF",
    profile: "Profile",
    account: "Account",
    memberSince: "Member Since",
    usageReport: "Usage Report",
    dailyReport: "Daily Report",
    monthlyReport: "Monthly Report",
    scanning: "Scanning...",
    syncing: "Syncing...",
    battery: "Battery",
    location: "Location",
    continueWithGoogle: "Continue with Google",
    orContinueWith: "Or continue with",
    orTryDemo: "Or try demo",
    dashboardSubtitle: "Monitor your water consumption in real-time",
    loginSubtitle: "Email and password, or Google.",
    registerSubtitle: "Register with email and password, or Google.",
    signedInAs: "Signed in as",
    registerSignedInNote: "Sign out first if you need a different email.",
    forgotPassword: "Forgot password?",
    authNoAccount: "Don't have an account?",
    authHaveAccount: "Already have an account?",
    passwordMismatch: "Passwords do not match",
    passwordMinLength: "Password must be at least 6 characters",
    firebaseNotConfigured:
      "Firebase is not configured. Add NEXT_PUBLIC_FIREBASE_* keys to .env.local (see .env.example).",
    devicesLine: "{n} devices — BLE (ESP32-C6 + YF-B7)",
    devicesBleStack: "BLE (ESP32-C6 + YF-B7)",
    devicesEmptyHint:
      "Scan for your ESP32-C6 (SmartFaucet BLE). Flow data appears on the dashboard after connect.",
    pairDialogDescription:
      "Scan for ESP32-C6 running SmartFaucet firmware (YF-B7 flow sensor). Grant Bluetooth when asked.",
    bleScanningTitle: "Scanning for BLE peripherals…",
    bleScanningHint: "~12 seconds · power ESP32 first",
    foundLabel: "Found",
    connect: "Connect",
    historySubtitle: "Daily cold water usage (liters) and cost",
    historyDailyColdDesc: "Daily cold water (liters)",
    historyDailySpendDesc: "Daily spending",
    noHistoryData: "No history data yet",
    noCostTrendData: "No cost trend data yet",
    chartUsageTrend: "Usage Trend",
    chartLast6MonthsWater: "Last 6 months water consumption",
    chartCostTrend: "Cost Trend",
    chartLast6MonthsSpend: "Last 6 months spending",
    noUsageData: "No usage data yet",
    noCostData: "No cost data yet",
    weeklyComparison: "Weekly Comparison",
    weeklyComparisonDesc: "Last 4 weeks water consumption and daily average",
    noWeeklyData: "No weekly data yet",
    chartTotalUsage: "Total Usage",
    chartDailyAvg: "Daily Avg",
    smartSuggestions: "Smart Suggestions",
    smartSuggestionsDesc: "Recommendations based on your usage patterns",
    noAiSuggestions: "No suggestions yet — data will appear when usage is available.",
    ecoGreat: "Great job! You're using less water than average",
    ecoNormal: "Your usage is within normal range",
    ecoHigh: "Consider reducing water usage",
    tooltipUsage: "Usage",
    analyticsPageSubtitle: "Analyze your water consumption patterns and find ways to save",
    savingTipsDesc: "Simple ways to reduce water use and save money",
    profileAccountDesc: "Manage your account information",
    notificationsSettingsDesc: "Manage push notification settings",
    notifEnabledStatus: "Notifications are enabled",
    notifBlockedStatus: "Notifications are blocked",
    notifPromptStatus: "Enable browser notifications",
    notifEnableInBrowserSettings: "Please enable notifications in your browser settings",
    exportDataDesc: "Download your water usage data",
    dailyReportDesc: "Last 7 days of usage data",
    monthlyReportDesc: "6 months of historical data",
    exportJSONLabel: "Export JSON",
    loading: "Loading…",
    redirectingToSignIn: "Redirecting to sign in…",
    resetPassword: "Reset Password",
    resetPasswordEnterEmail: "Enter your email address and we'll send you a link to reset your password.",
    resetPasswordEmailSent: "Email sent",
    resetPasswordEmailSentBody:
      "If an account exists for {email}, you will receive a password reset link shortly.",
    resetPasswordCheckEmailInstructions:
      "Please check your inbox and follow the instructions in the email to reset your password.",
    sendResetLink: "Send reset link",
    backToLogin: "Back to Login",
    emailPlaceholder: "your@email.com",
    authErrorTitle: "Authentication error",
    authErrorSomethingWrong: "Something went wrong during sign in. Please try again.",
    authErrorWithCode: "Error: {error}",
    chartLitersPerDay: "L/day",
  },
  mn: {
    dashboard: "Самбар",
    control: "Удирдлага",
    history: "Түүх",
    analytics: "Дүн шинжилгээ",
    presets: "Тохиргоонууд",
    settings: "Тохиргоо",
    realTimeUsage: "Шууд хэрэглээ",
    waterFlow: "Усны урсгал",
    temperature: "Халуун",
    cost: "Төлбөр",
    liters: "Литр",
    cold: "Хүйтэн",
    warm: "Бүлээн",
    hot: "Халуун",
    currentUsage: "Одоогийн хэрэглээ",
    todayUsage: "Өнөөдрийн хэрэглээ",
    monthlyUsage: "Сарын хэрэглээ",
    waterControl: "Ус удирдах",
    setTemperature: "Халуун тохируулах",
    setLimit: "Хязгаар тавих",
    byLiters: "Литрээр",
    byTime: "Хугацаагаар",
    estimatedCost: "Төсөөлсөн төлбөр",
    start: "Эхлүүлэх",
    stop: "Зогсоох",
    safety: "Аюулгүй байдал",
    notifications: "Мэдэгдэл",
    overuseAlert: "Их хэрэглэсэн анхааруулга",
    normalUsage: "Хэвийн хэрэглээ",
    limitExceeded: "Хязгаар давсан",
    usageHistory: "Хэрэглээний түүх",
    last7Days: "Сүүлийн 7 хоног",
    coldWater: "Хүйтэн ус",
    warmWater: "Бүлээн ус",
    hotWater: "Халуун ус",
    monthlyComparison: "Сарын харьцуулалт",
    currentMonth: "Энэ сар",
    lastMonth: "Өмнөх сар",
    increase: "Өсөлт",
    decrease: "Бууралт",
    ecoEfficiency: "Экологийн үр ашиг",
    good: "Сайн",
    average: "Дундаж",
    high: "Өндөр",
    savingTips: "Ус хэмнэх зөвлөгөө",
    smartPresets: "Ухаалаг тохиргоо",
    shower: "Шүршүүр",
    bath: "Ванн",
    kitchen: "Гал тогоо",
    edit: "Засах",
    save: "Хадгалах",
    cancel: "Болих",
    costEfficiency: "Зардлын үр ашиг",
    low: "Бага",
    medium: "Дунд",
    language: "Хэл",
    currencyLabel: "Мөнгөн тэмдэгт",
    minutes: "мин",
    seconds: "сек",
    flowRate: "Урсгалын хурд",
    perMinute: "/ мин",
    active: "Идэвхтэй",
    inactive: "Идэвхгүй",
    autoShutoff: "Автомат унтраалт",
    enabled: "Асаалттай",
    disabled: "Унтраалттай",
    selectPreset: "Тохиргоо сонгох",
    customSettings: "Өөрийн тохиргоо",
    applyPreset: "Тохиргоо ашиглах",
    editPreset: "Тохиргоо засах",
    presetName: "Тохиргооны нэр",
    temperatureRange: "Халууны хүрээ",
    waterLimit: "Усны хязгаар",
    duration: "Хугацаа",
    close: "Хаах",
    login: "Нэвтрэх",
    register: "Бүртгүүлэх",
    logout: "Гарах",
    email: "Имэйл хаяг",
    password: "Нууц үг",
    confirmPassword: "Нууц үг давтах",
    name: "Нэр",
    welcomeBack: "Тавтай морилно уу",
    createAccount: "Шинэ бүртгэл",
    demoCredentials: "Туршилтын мэдээлэл",
    devices: "Төхөөрөмж",
    scanDevices: "Төхөөрөмж хайх",
    noDevices: "Төхөөрөмж олдсонгүй",
    pairDevice: "Холбох",
    removeDevice: "Устгах",
    syncDevice: "Шинэчлэх",
    deviceStatus: "Төхөөрөмжийн байдал",
    online: "Холбогдсон",
    offline: "Салсан",
    signalStrength: "Дохионы хүч",
    firmwareVersion: "Програмын хувилбар",
    lastSeen: "Сүүлд харагдсан",
    connectionLogs: "Холболтын түүх",
    markAllRead: "Бүгдийг уншсан болгох",
    clearAll: "Бүгдийг устгах",
    noNotifications: "Мэдэгдэл алга",
    enableNotifications: "Мэдэгдэл идэвхжүүлэх",
    export: "Татах",
    exportCSV: "CSV татах",
    exportPDF: "PDF татах",
    profile: "Профайл",
    account: "Бүртгэл",
    memberSince: "Бүртгүүлсэн",
    usageReport: "Хэрэглээний тайлан",
    dailyReport: "Өдрийн тайлан",
    monthlyReport: "Сарын тайлан",
    scanning: "Хайж байна...",
    syncing: "Шинэчилж байна...",
    battery: "Батарей",
    location: "Байршил",
    continueWithGoogle: "Google-ээр үргэлжлүүлэх",
    orContinueWith: "Эсвэл",
    orTryDemo: "Туршилтаар нэвтрэх",
    dashboardSubtitle: "Усны хэрэглээг шууд хянах",
    loginSubtitle: "Имэйл, нууц үг эсвэл Google.",
    registerSubtitle: "Имэйл, нууц үгээр бүртгүүлэх эсвэл Google.",
    signedInAs: "Нэвтэрсэн",
    registerSignedInNote: "Өөр имэйл хэрэгтэй бол эхлээд гарна уу.",
    forgotPassword: "Нууц үгээ мартсан уу?",
    authNoAccount: "Бүртгэл байхгүй юу?",
    authHaveAccount: "Бүртгэлтэй юу?",
    passwordMismatch: "Нууц үг таарахгүй байна",
    passwordMinLength: "Нууц үг хамгийн багадаа 6 тэмдэгт",
    firebaseNotConfigured:
      "Firebase тохируулаагүй. .env.local дээр NEXT_PUBLIC_FIREBASE_* нэмнэ үү (.env.example).",
    devicesLine: "{n} төхөөрөмж — BLE (ESP32-C6 + YF-B7)",
    devicesBleStack: "BLE (ESP32-C6 + YF-B7)",
    devicesEmptyHint:
      "ESP32-C6 (SmartFaucet BLE) хайна уу. Холбосны дараа урсгал самбарт харагдана.",
    pairDialogDescription:
      "SmartFaucet суурь програмтой ESP32-C6 (YF-B7 мэдрэгч)-ийг хайна. Bluetooth зөвшөөрнө үү.",
    bleScanningTitle: "BLE төхөөрөмж хайж байна…",
    bleScanningHint: "~12 сек · эхлээд ESP32 асаана уу",
    foundLabel: "Олдсон",
    connect: "Холбох",
    historySubtitle: "Өдөр тутмын хүйтэн ус (литр) ба зардал",
    historyDailyColdDesc: "Өдрийн хүйтэн ус (литр)",
    historyDailySpendDesc: "Өдрийн зардал",
    noHistoryData: "Түүхийн өгөгдөл алга",
    noCostTrendData: "Зардлын чиг хандлага алга",
    chartUsageTrend: "Хэрэглээний чиг хандлага",
    chartLast6MonthsWater: "Сүүлийн 6 сарын усны хэрэглээ",
    chartCostTrend: "Зардлын чиг хандлага",
    chartLast6MonthsSpend: "Сүүлийн 6 сарын зардал",
    noUsageData: "Хэрэглээний өгөгдөл алга",
    noCostData: "Зардлын өгөгдөл алга",
    weeklyComparison: "7 хоногийн харьцуулалт",
    weeklyComparisonDesc: "Сүүлийн 4 долоо хоногийн хэрэглээ, өдрийн дундаж",
    noWeeklyData: "Долоо хоногийн өгөгдөл алга",
    chartTotalUsage: "Нийт хэрэглээ",
    chartDailyAvg: "Өдрийн дундаж",
    smartSuggestions: "Ухаалаг зөвлөмж",
    smartSuggestionsDesc: "Таны хэрэглээнд үндэслэсэн зөвлөмж",
    noAiSuggestions: "Зөвлөмж алга — хэрэглээний өгөгдөл нэмэгдэхэд харагдана.",
    ecoGreat: "Сайн! Дунджаас бага ус хэрэглэж байна",
    ecoNormal: "Хэрэглээ хэвийн хэмжээнд байна",
    ecoHigh: "Усны хэрэглээг бууруулахыг зөвлөж байна",
    tooltipUsage: "Хэрэглээ",
    analyticsPageSubtitle: "Усны хэрэглээний хэв маягийг шинжилж, хэмнэлтийн арга олоорой",
    savingTipsDesc: "Ус бага зарцуулж, мөнгө хэмнэх энгийн аргууд",
    profileAccountDesc: "Бүртгэлийн мэдээллээ удирдах",
    notificationsSettingsDesc: "Push мэдэгдлийн тохиргоо",
    notifEnabledStatus: "Мэдэгдэл асаалттай",
    notifBlockedStatus: "Мэдэгдэл хориглогдсон",
    notifPromptStatus: "Хөтөчийн мэдэгдлийг идэвхжүүлнэ үү",
    notifEnableInBrowserSettings: "Хөтөчийн тохиргооноос мэдэгдлийг зөвшөөрнө үү",
    exportDataDesc: "Усны хэрэглээний өгөгдлийг татах",
    dailyReportDesc: "Сүүлийн 7 хоногийн өгөгдөл",
    monthlyReportDesc: "Сүүлийн 6 сарын түүхийн өгөгдөл",
    exportJSONLabel: "JSON татах",
    loading: "Ачааллаж байна…",
    redirectingToSignIn: "Нэвтрэх хуудас руу шилжиж байна…",
    resetPassword: "Нууц үг сэргээх",
    resetPasswordEnterEmail:
      "Имэйл хаягаа оруулбал нууц үг сэргээх холбоос илгээнэ.",
    resetPasswordEmailSent: "Имэйл илгээгдлээ",
    resetPasswordEmailSentBody:
      "{email} хаягт бүртгэл байвал удахгүй нууц үг сэргээх холбоос ирнэ.",
    resetPasswordCheckEmailInstructions:
      "Имэйл хайрцаг шалгаад, зааврын дагуу нууц үгээ сэргээнэ үү.",
    sendResetLink: "Сэргээх холбоос илгээх",
    backToLogin: "Нэвтрэлт рүү буцах",
    emailPlaceholder: "your@email.com",
    authErrorTitle: "Нэвтрэх алдаа",
    authErrorSomethingWrong: "Нэвтрэх үед алдаа гарлаа. Дахин оролдоно уу.",
    authErrorWithCode: "Алдаа: {error}",
    chartLitersPerDay: "Л/өдөр",
  },
}

const currencyRates: Record<Currency, number> = {
  JPY: 1,
  USD: 0.0067,
  MNT: 22.5,
}

const currencySymbols: Record<Currency, string> = {
  JPY: "¥",
  USD: "$",
  MNT: "₮",
}

const SettingsContext = createContext<SettingsContextType | undefined>(undefined)

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("mn")
  const [currency, setCurrency] = useState<Currency>("MNT")

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  const formatCurrency = (amountInJPY: number): string => {
    const converted = amountInJPY * currencyRates[currency]
    const symbol = currencySymbols[currency]
    if (currency === "JPY") {
      return `${symbol}${Math.round(converted).toLocaleString()}`
    }
    return `${symbol}${converted.toFixed(2)}`
  }

  return (
    <SettingsContext.Provider
      value={{ language, setLanguage, currency, setCurrency, t, formatCurrency }}
    >
      {children}
    </SettingsContext.Provider>
  )
}

export function useSettings() {
  const context = useContext(SettingsContext)
  if (!context) {
    throw new Error("useSettings must be used within a SettingsProvider")
  }
  return context
}
